name: CI Workflow
on: [push, pull_request]

jobs:
  ci_job:
    name: CI Job
    runs-on: ubuntu-16.04
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '10.x'

      - name: Checkout source code
        uses: actions/checkout@v2
  
      - name: Install dependencies
        run: yarn install
              
      - name: Build
        run: yarn build:ci

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci
